AR := ar
CC := gcc

CFLAGS = -I./libusb -I./tpl -I/usr/local/include -I/opt/local/include
LDFLAGS = -L/usr/lib -L/opt/local/lib 
LIBS = -lusb-1.0

LIBIRPC_TARGET = libirpc.a
LIBIRPC_OBJECTS = libirpc.o tpl/tpl.c
LIBIRPC_CFLAGS = $(CFLAGS)
LIBIRPC_LDFLAGS = $(LDFLAGS)
LIBIRPC_LIBS = $(LIBS)

IRPC_CLIENT_TARGET = irpc_client
IRPC_CLIENT_OBJECTS = irpc_client.o tpl/tpl.c libirpc.a
IRPC_CLIENT_CFLAGS = $(CFLAGS)
IRPC_CLIENT_LDFLAGS = $(LDFLAGS)
IRPC_CLIENT_LIBS = $(LIBS)

IRPC_SERVER_TARGET = irpc_server
IRPC_SERVER_OBJECTS = irpc_server.o tpl/tpl.c libirpc.a
IRPC_SERVER_CFLAGS = $(CFLAGS)
IRPC_SERVER_LDFLAGS = $(LDFLAGS)
IRPC_SERVER_LIBS = $(LIBS)

TARGETS = $(LIBIRPC_TARGET) $(IRPC_CLIENT_TARGET) $(IRPC_SERVER_TARGET)
OBJECTS = $(LIBIRPC_OBJECTS) $(IRPC_CLIENT_OBJECTS) $(IRPC_SERVER_OBJECTS)

%.o: %.S
	$(CC) -c $(<) -o $(@) $(CFLAGS)

%.o: %.c
	$(CC) -c $(<) -o $(@) $(CFLAGS)

$(LIBIRPC_TARGET): $(LIBIRPC_OBJECTS)
	$(AR) rs $(LIBIRPC_TARGET) $(LIBIRPC_OBJECTS)

$(IRPC_CLIENT_TARGET): $(IRPC_CLIENT_OBJECTS)
	$(CC) -o $(IRPC_CLIENT_TARGET) $(IRPC_CLIENT_OBJECTS) $(IRPC_CLIENT_CFLAGS) $(IRPC_CLIENT_LDFLAGS) $(IRPC_CLIENT_LIBS)

$(IRPC_SERVER_TARGET): $(IRPC_SERVER_OBJECTS)
	$(CC) -o $(IRPC_SERVER_TARGET) $(IRPC_SERVER_OBJECTS) $(IRPC_SERVER_CFLAGS) $(IRPC_SERVER_LDFLAGS) $(IRPC_SERVER_LIBS)

all: $(TARGETS)
		
clean:
	$(RM) $(LIBIRPC_TARGET) $(IRPC_CLIENT_TARGET) $(IRPC_SERVER_TARGET) *.o
